import dotenv from 'dotenv';
import { BrevoClient } from '@getbrevo/brevo';

// Load environment variables (BREVO_API_KEY, SENDER_EMAIL)
dotenv.config();

// Initialize Brevo client with API key from environment
const brevo = new BrevoClient({
  apiKey: process.env.BREVO_API_KEY as string,
});

// Sends a generic transactional notification email (booking updates, etc.)
export const sendNotificationEmail = async (
  toEmail: string,
  title: string,
  body: string
) => {
  try {
    await brevo.transactionalEmails.sendTransacEmail({
      to: [{ email: toEmail }],
      sender: {
        email: process.env.SENDER_EMAIL as string,
        name: 'SpaceShare',
      },
      subject: title,
      htmlContent: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #6200EE;">${title}</h2>
          <p>${body}</p>
        </div>
      `,
    });
  } catch (err: any) {
    // Log but don't throw — email failure shouldn't block the rest of the notification flow
    console.log('Failed to send notification email:', err?.response?.data ?? err.message);
  }
};
// Sends a transactional email containing a one-time verification code
export const sendVerificationEmail = async (
  toEmail: string,
  code: string    // 6-digit OTP generated by the caller
) => {
  await brevo.transactionalEmails.sendTransacEmail({
    to: [{ email: toEmail }],
    sender: {
      email: process.env.SENDER_EMAIL as string,
      name: 'SpaceShare',
    },
    subject: 'Verify your SpaceShare account',
    // Inline styles used for broad email client compatibility
    htmlContent: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #6200EE;">Verify your email</h2>
        <p>Your verification code is:</p>
        <h1 style="color: #6200EE; letter-spacing: 8px;">${code}</h1>
        <p>This code expires in <strong>10 minutes</strong>.</p>
        <p>If you didn't create a SpaceShare account, ignore this email.</p>
      </div>
    `,
  });
};

//Sends verification email to admin
export const sendVerificationEmailLink = async (
  toEmail: string,
  verificationLink: string
) => {
  await brevo.transactionalEmails.sendTransacEmail({
    to: [{ email: toEmail }],
    sender: {
      email: process.env.SENDER_EMAIL as string,
      name: 'SpaceShare',
    },
    subject: 'Verify your SpaceShare account',
    // Inline styles used for broad email client compatibility
    htmlContent: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #6200EE;">Verify your email</h2>
        <p>Click the link below:</p>
        <a href="${verificationLink}" target="_blank" style="color: #6200EE; letter-spacing: 1px;">Verify your account</a>
        <p>This verification link expires in <strong>10 minutes</strong>.</p>
        <p>If you do not possess a Spaceshare account and did not request for this, kindly ignore this email.</p>
      </div>
    `,
  });
};
